# NPM COMMANDS

npm_install:
	# Install react dependencies
	npm install

npm_start:
	# Start a dev server for the applications.
	npm start

npm_run_build:
	# Creating productino build of the application.
	npm run build